### ISSUE TITLE
Possible little typos/inconsistencies in code and documentation

### ISSUE THREAD

**Issue by enricoteofilo** [hemantaph/ler#10]
Hi. 
It's possible that the LeR class and the documentation both contain some typos/inconsistencies to each other.

Ones I've found:
- [x] in the LeR class a method is called `rate_comparision_with_rate_calculation `instead of `rate_comparison_with_rate_calculation` as in the example in the documentation
- [x] in the documentation > Installation: when installing through a **new conda environment**, the new created environment is called `ler2`, and not `ler` as in the written instructions
- [x] in the documentation there are some references to the `CompactBinaryPopulation` class, which I think is not present in the code anymore and has been superceeded by `CBCSourceParameterDistribution` (but I may be wrong...)

**Comment by hemantaph** [comment]
Thanks for the comments

* I have it changed to  'rate_comparison_with_rate_calculation' in git and documentation. And I will update pypi after a couple of days.
*  In the ler.yml file, ler2 is changed to ler
* all CompactBinaryPopulation text changed to CBCSourceParameterDistribution.

**Comment by enricoteofilo** [comment]
Hello.
I have an additional question on the documentation.

From the documentation it wasn't totally clear to me how to get from `x0_image_positions` and `x1_image_positions` to the (_effective_) _ra,dec_ coordinates of individual lensed images.

Please, can you better clarify?
Thank you
